# docker-compose.yml
version: '3.8'

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

  # Сервис бэкенда
  backend:
    build: ./backend
    restart: unless-stopped
    volumes:
      - ./backend/app:/app/app # Пробрасываем код для удобной разработки
    command: >
      sh -c "alembic upgrade head && 
             gunicorn -k uvicorn.workers.UvicornWorker -w 4 app.main:app --bind 0.0.0.0:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

  # Сервис фронтенда (Nginx)
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80" # Пробрасываем порт 80 сервера на порт 80 контейнера
    depends_on:
      - backend

volumes:
  postgres_data: