# docker-compose.yml
version: '3.7' # Оставляем совместимую версию

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

  # Сервис бэкенда
  backend:
    build: ./backend
    restart: unless-stopped
    command: >
      sh -c "sleep 10 && alembic upgrade head && 
             gunicorn -k uvicorn.workers.UvicornWorker -w 4 app.main:app --bind 0.0.0.0:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    
    # --- ИСПРАВЛЕНИЕ ЗДЕСЬ ---
    # Используем простой формат списка
    depends_on:
      - db

  # Сервис фронтенда (Nginx)
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  postgres_data: