"""Add authentication and user ownership to Briefs

Revision ID: 3496f6656ba9
Revises: 0b6582f22780
Create Date: 2025-06-06 14:31:12.913431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3496f6656ba9'
down_revision: Union[str, None] = '0b6582f22780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
