"""Re-generate initial tables

Revision ID: 44710a4ebdb3
Revises: 7ee39049f95c
Create Date: 2025-06-04 15:38:17.386831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44710a4ebdb3'
down_revision: Union[str, None] = '7ee39049f95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
