"""Add steps model and update relationships

Revision ID: 5b99d7650075
Revises: 7a7e9f3fc37b
Create Date: 2025-06-05 14:54:23.897513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b99d7650075'
down_revision: Union[str, None] = '7a7e9f3fc37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_id'), 'steps', ['id'], unique=False)
    op.add_column('questions', sa.Column('step_id', sa.Integer(), nullable=False))
    op.drop_constraint('questions_brief_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'steps', ['step_id'], ['id'])
    op.drop_column('questions', 'brief_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('brief_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_brief_id_fkey', 'questions', 'briefs', ['brief_id'], ['id'])
    op.drop_column('questions', 'step_id')
    op.drop_index(op.f('ix_steps_id'), table_name='steps')
    op.drop_table('steps')
    # ### end Alembic commands ###
