"""Add description to Step model

Revision ID: 6dde026aa09e
Revises: b5d7af6734b4
Create Date: 2025-06-09 10:50:14.576430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dde026aa09e'
down_revision: Union[str, None] = 'b5d7af6734b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'description')
    # ### end Alembic commands ###
