"""Add created_at and updated_at to Question model (final attempt)

Revision ID: 7a7e9f3fc37b
Revises: 44710a4ebdb3
Create Date: 2025-06-04 16:12:52.142035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7e9f3fc37b'
down_revision: Union[str, None] = '44710a4ebdb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    # ### end Alembic commands ###
