"""Add conditional_logic to Step model

Revision ID: 85950f7ddbbd
Revises: 8e3624e8693d
Create Date: 2025-06-05 17:21:57.849694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85950f7ddbbd'
down_revision: Union[str, None] = '8e3624e8693d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
