"""Add user ownership to briefs

Revision ID: b5d7af6734b4
Revises: 3496f6656ba9
Create Date: 2025-06-08 10:51:36.852525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = 'b5d7af6734b4'
down_revision: Union[str, None] = '3496f6656ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_answers_id', table_name='user_answers')
    op.drop_index('ix_user_answers_session_id', table_name='user_answers')
    op.drop_table('user_answers')
    op.add_column('briefs', sa.Column('is_main', sa.Boolean(), server_default=text('false'), nullable=False))
    op.add_column('briefs', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'briefs', 'users', ['owner_id'], ['id'])
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'briefs', type_='foreignkey')
    op.drop_column('briefs', 'owner_id')
    op.drop_column('briefs', 'is_main')
    op.create_table('user_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brief_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answers_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], name='user_answers_brief_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_answers_pkey')
    )
    op.create_index('ix_user_answers_session_id', 'user_answers', ['session_id'], unique=False)
    op.create_index('ix_user_answers_id', 'user_answers', ['id'], unique=False)
    # ### end Alembic commands ###
