"""Add conditional_logic to Step model

Revision ID: e120a1699678
Revises: 5b99d7650075
Create Date: 2025-06-05 16:55:02.201642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e120a1699678'
down_revision: Union[str, None] = '5b99d7650075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('conditional_logic', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'conditional_logic')
    # ### end Alembic commands ###
