"""Add conditional_logic to Step model

Revision ID: fc525177f2c7
Revises: 85950f7ddbbd
Create Date: 2025-06-05 17:28:06.959236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc525177f2c7'
down_revision: Union[str, None] = '85950f7ddbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
